export default [
  {
    id: 1,
    picture: 'https://png.pngtree.com/png-clipart/20210915/ourmid/pngtree-user-avatar-login-interface-abstract-blue-icon-png-image_3917504.jpg',
    title: 'Annonce',
    zipcode: '34090',
    city: 'Montpellier',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas non est sit amet felis finibus maximus. Proin vel fermentum mauris, a faucibus risus. Duis at urna nec turpis luctus varius ac non est. Aliquam a est dapibus, cursus ex et, egestas justo. Curabitur vel magna mollis, pharetra arcu non, commodo neque. Mauris sapien sem, facilisis quis nunc et, lacinia maximus massa. Duis eros elit, egestas ac libero at, eleifend mollis mi.',
    date: Date.now(),
  },
  {
    id: 2,
    picture: 'https://png.pngtree.com/png-clipart/20210915/ourmid/pngtree-user-avatar-login-interface-abstract-blue-icon-png-image_3917504.jpg',
    title: 'Annonce',
    zipcode: '34090',
    city: 'Montpellier',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas non est sit amet felis finibus maximus. Proin vel fermentum mauris, a faucibus risus. Duis at urna nec turpis luctus varius ac non est. Aliquam a est dapibus, cursus ex et, egestas justo. Curabitur vel magna mollis, pharetra arcu non, commodo neque. Mauris sapien sem, facilisis quis nunc et, lacinia maximus massa. Duis eros elit, egestas ac libero at, eleifend mollis mi.',
    date: Date.now(),
  },
  {
    id: 3,
    picture: 'https://png.pngtree.com/png-clipart/20210915/ourmid/pngtree-user-avatar-login-interface-abstract-blue-icon-png-image_3917504.jpg',
    title: 'Annonce',
    zipcode: '34090',
    city: 'Montpellier',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas non est sit amet felis finibus maximus. Proin vel fermentum mauris, a faucibus risus. Duis at urna nec turpis luctus varius ac non est. Aliquam a est dapibus, cursus ex et, egestas justo. Curabitur vel magna mollis, pharetra arcu non, commodo neque. Mauris sapien sem, facilisis quis nunc et, lacinia maximus massa. Duis eros elit, egestas ac libero at, eleifend mollis mi.',
    date: Date.now(),
  },
  {
    id: 4,
    picture: 'https://png.pngtree.com/png-clipart/20210915/ourmid/pngtree-user-avatar-login-interface-abstract-blue-icon-png-image_3917504.jpg',
    title: 'Annonce',
    zipcode: '34090',
    city: 'Montpellier',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas non est sit amet felis finibus maximus. Proin vel fermentum mauris, a faucibus risus. Duis at urna nec turpis luctus varius ac non est. Aliquam a est dapibus, cursus ex et, egestas justo. Curabitur vel magna mollis, pharetra arcu non, commodo neque. Mauris sapien sem, facilisis quis nunc et, lacinia maximus massa. Duis eros elit, egestas ac libero at, eleifend mollis mi.',
    date: Date.now(),
  },
];
